[package]
name = "storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono = "0.4"
uuid = { version = "1.11", features = ["v4", "serde"] }
