apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zyvor-fabric.fullname" . }}-config
  labels:
    {{- include "zyvor-fabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: fabricd
data:
  zyvor-fabricd.toml: |
    {{- .Values.fabricd.config | nindent 4 }}
