{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zyvor-fabric.fullname" . }}-secrets
  labels:
    {{- include "zyvor-fabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  admin-username: {{ .Values.security.adminUsername | default "admin" | quote }}
  admin-password: {{ .Values.security.adminPassword | default "Admin@321" | quote }}
  jwt-secret: {{ .Values.security.jwtSecret | default "zyvor-fabric-lab-jwt-change-me" | quote }}
{{- end }}
