{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zyvor-fabric.fullname" . }}-secrets
  labels:
    {{- include "zyvor-fabric.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "security.adminPassword is required (or set security.existingSecret)" .Values.security.adminPassword | quote }}
  jwt-secret: {{ required "security.jwtSecret is required (or set security.existingSecret)" .Values.security.jwtSecret | quote }}
{{- end }}
