[package]
name = "vmspawnd-machinectl-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
tokio.workspace = true
chrono.workspace = true
zbus.workspace = true
async-stream.workspace = true
async-trait.workspace = true
vm-model = { path = "../../vm-model" }
zyvor-fabric-driver-core = { path = "../driver-core" }
vmspawnd-machined-dbus = { path = "../machined-dbus" }
zyvor-fabric-cgroup = { path = "../cgroup" }
zyvor-fabric-vm-driver = { path = "../../zyvor-fabric-vm-driver" }
