#!/usr/bin/env python3
"""Regenerates Sources/KeepKit/CatalogData.swift from examples/keep-agents/*/pack.json and their READMEs.

usage: gen_catalog.py [path-to-examples/keep-agents]   (default: ../../examples/keep-agents from this file)
The catalogue only adds a group, and a "how to get this file" command, to what the host's GET /v1/demos already lists.
"""
import json, os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "..", "..", "examples", "keep-agents")
out = os.path.join(here, "..", "Sources", "KeepKit", "CatalogData.swift")

GROUPS = {
    "documents": "pdf-brief contract-clauses security-questionnaire meeting-actions meeting-notes-model nda-review receipt-pdf invoice-model-brief deck-outline api-facts invoice-check inbox-digest status-page-watch mailbox-triage csv-clean".split(),
    "phone": "chat-export-digest bank-sms-ledger card-statement calendar-week contacts-audit travel-itinerary subscription-finder android-call-log".split(),
    "mac": "mac-system-report homebrew-audit mac-log-triage mac-update-history mac-apps-inventory mac-launch-items".split(),
    "windows": "windows-systeminfo windows-hotfixes windows-installed-software windows-event-log windows-services windows-scheduled-tasks".split(),
    "developer": "github-prs github-issues github-actions-log dependabot-alerts git-log-digest xcodebuild-log xcode-crash-log vscode-extensions vscode-settings-audit log-triage sbom-summary".split(),
    "browser": "bookmarks-digest browser-history-takeout takeout-my-activity".split(),
    "office": "receivables-ageing po-line-items employee-ledger reimbursement-claims sales-register-sheet inventory-sheet attendance-sheet expense-sheet payslip-text".split(),
}
group_of = {pack: g for g, packs in GROUPS.items() for pack in packs}

def hint(readme):
    """The first fenced code block's commands, minus the keepctl lines: how the person gets the file."""
    m = re.search(r"```(?:bash|sh|powershell)\n(.*?)```", readme, re.S)
    if not m:
        return None
    lines = [l.rstrip() for l in m.group(1).splitlines() if l.strip() and "keepctl" not in l]
    return " ".join(lines[:4]) if lines else None

def swift(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

entries = []
for name in sorted(os.listdir(root)):
    p = os.path.join(root, name, "pack.json")
    if not os.path.isfile(p):
        continue
    spec = json.load(open(p))
    if spec.get("kind") != "usecase":
        continue
    rp = os.path.join(root, name, "README.md")
    h = hint(open(rp).read()) if os.path.isfile(rp) else None
    entries.append((name, group_of.get(name, "other"), h))

# the built-in use cases live in the runtime, not in examples/
builtins = [("pdf-brief", "documents"), ("contract-clauses", "documents"), ("security-questionnaire", "documents"),
            ("meeting-actions", "documents"), ("log-triage", "developer"), ("sbom-summary", "developer"), ("csv-clean", "documents")]
seen = {e[0] for e in entries}
for name, g in builtins:
    if name not in seen:
        entries.append((name, g, None))
entries.sort()

lines = ["// Generated by tools/gen_catalog.py from examples/keep-agents. Do not edit by hand.", "",
         "extension Catalog {", "    static let generated: [CatalogEntry] = ["]
for name, g, h in entries:
    lines.append(f"        CatalogEntry(id: {swift(name)}, group: .{g}, howToGetFile: {swift(h) if h else 'nil'}),")
lines += ["    ]", "}", ""]
open(out, "w").write("\n".join(lines))
print(f"{len(entries)} entries -> {os.path.relpath(out)}")
