name: Feature request
description: Propose an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Suggested priority
      options: [P0, P1, P2, unknown]
