// Copyright 2026 Zyvor
// SPDX-License-Identifier: Apache-2.0

use anyhow::Result;
use tracing;

use crate::models::*;

/// Where zone hosts-files live -- also passed to each bridge's dnsmasq
/// instance as `--hostsdir` (see `zyvor_fabric_dnsmasq_manager`) so VMs on
/// a bridge with DHCP configured can resolve zone records automatically.
pub const DNS_DIR: &str = "/etc/zyvor-fabricd/dns";

/// Writes DNS records to hosts-format zone files.
///
/// Strategy:
/// - Write zone files to `/etc/zyvor-fabricd/dns/<zone>.hosts`
/// - Each file contains hosts-format entries: `<IP> <FQDN>`
pub struct DnsEnforcer;

impl DnsEnforcer {
    pub fn new() -> Self {
        Self
    }

    /// Sync DNS records grouped by zone.
    pub fn sync_records(&self, records: &[DnsRecord], zones: &[DnsZone]) -> Result<()> {
        // Ensure DNS directory exists
        std::fs::create_dir_all(DNS_DIR)
            .map_err(|e| anyhow::anyhow!("Failed to create DNS directory {}: {}", DNS_DIR, e))?;

        // Group records by zone (matching by FQDN suffix)
        let mut zone_records: std::collections::HashMap<String, Vec<&DnsRecord>> =
            std::collections::HashMap::new();

        for zone in zones {
            zone_records.insert(zone.name.clone(), Vec::new());
        }

        for record in records {
            for zone in zones {
                if record.name.ends_with(&zone.name) {
                    zone_records
                        .entry(zone.name.clone())
                        .or_default()
                        .push(record);
                    break;
                }
            }
        }

        // Write each zone file
        for (zone_name, records) in &zone_records {
            self.write_zone_file(zone_name, records)?;
        }

        tracing::info!(
            "Synced {} DNS records across {} zones",
            records.len(),
            zones.len()
        );
        Ok(())
    }

    /// Write a zone file in hosts format.
    pub fn write_zone_file(&self, zone_name: &str, records: &[&DnsRecord]) -> Result<()> {
        if zone_name.contains('/') || zone_name.contains("..") {
            return Err(anyhow::anyhow!("Invalid zone name"));
        }

        let mut content = String::new();
        content.push_str(&format!("# DNS zone: {}\n", zone_name));
        content.push_str("# Auto-generated by zyvor-fabricd — do not edit\n\n");

        for record in records {
            content.push_str(&self.build_hosts_entry(record));
            content.push('\n');
        }

        let file_path = format!("{}/{}.hosts", DNS_DIR, zone_name);
        std::fs::write(&file_path, &content)
            .map_err(|e| anyhow::anyhow!("Failed to write zone file {}: {}", file_path, e))?;

        tracing::debug!("Wrote {} records to {}", records.len(), file_path);
        Ok(())
    }

    /// Remove all zone files.
    pub fn cleanup(&self) -> Result<()> {
        if let Ok(entries) = std::fs::read_dir(DNS_DIR) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().map(|e| e == "hosts").unwrap_or(false) {
                    let _ = std::fs::remove_file(&path);
                }
            }
        }
        tracing::info!("Cleaned up DNS zone files");
        Ok(())
    }

    /// Build a hosts-format entry for a DNS record.
    pub fn build_hosts_entry(&self, record: &DnsRecord) -> String {
        match record.record_type {
            DnsRecordType::A => {
                format!("{} {}", record.value, record.name)
            }
            DnsRecordType::Cname => {
                // hosts files don't natively support CNAME; emit as comment + A-like
                format!("# CNAME {} -> {}", record.name, record.value)
            }
            DnsRecordType::Srv => {
                // hosts files don't natively support SRV; emit as comment
                format!("# SRV {} {}", record.name, record.value)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_enforcer() -> DnsEnforcer {
        DnsEnforcer::new()
    }

    #[test]
    fn test_build_a_record_hosts_entry() {
        let enforcer = make_enforcer();
        let record = DnsRecord {
            name: "web-1.app-web.zyvor-fabricd.local".to_string(),
            record_type: DnsRecordType::A,
            value: "10.0.0.5".to_string(),
            ttl: 300,
            vm_name: "web-1".to_string(),
        };

        let entry = enforcer.build_hosts_entry(&record);
        assert_eq!(entry, "10.0.0.5 web-1.app-web.zyvor-fabricd.local");
    }

    #[test]
    fn test_srv_record() {
        let enforcer = make_enforcer();
        let record = DnsRecord {
            name: "_http._tcp.web.zyvor-fabricd.local".to_string(),
            record_type: DnsRecordType::Srv,
            value: "0 10 80 web-1.web.zyvor-fabricd.local".to_string(),
            ttl: 300,
            vm_name: "web-1".to_string(),
        };

        let entry = enforcer.build_hosts_entry(&record);
        assert!(entry.starts_with("# SRV"));
        assert!(entry.contains("_http._tcp.web.zyvor-fabricd.local"));
    }

    #[test]
    fn test_cname_record() {
        let enforcer = make_enforcer();
        let record = DnsRecord {
            name: "alias.zyvor-fabricd.local".to_string(),
            record_type: DnsRecordType::Cname,
            value: "web-1.web.zyvor-fabricd.local".to_string(),
            ttl: 300,
            vm_name: "web-1".to_string(),
        };

        let entry = enforcer.build_hosts_entry(&record);
        assert!(entry.starts_with("# CNAME"));
        assert!(entry.contains("alias.zyvor-fabricd.local"));
    }

    #[test]
    fn test_multiple_records_same_zone() {
        let enforcer = make_enforcer();
        let records = vec![
            DnsRecord {
                name: "web-1.web.zyvor-fabricd.local".to_string(),
                record_type: DnsRecordType::A,
                value: "10.0.0.5".to_string(),
                ttl: 300,
                vm_name: "web-1".to_string(),
            },
            DnsRecord {
                name: "web-2.web.zyvor-fabricd.local".to_string(),
                record_type: DnsRecordType::A,
                value: "10.0.0.6".to_string(),
                ttl: 300,
                vm_name: "web-2".to_string(),
            },
        ];

        let entry1 = enforcer.build_hosts_entry(&records[0]);
        let entry2 = enforcer.build_hosts_entry(&records[1]);
        assert!(entry1.contains("10.0.0.5"));
        assert!(entry2.contains("10.0.0.6"));
    }

    #[test]
    fn test_empty_zone() {
        let enforcer = make_enforcer();
        let empty: Vec<&DnsRecord> = vec![];
        // build_hosts_entry is per-record, so empty zone is just no calls
        assert_eq!(empty.len(), 0);
        // Verify the enforcer can be constructed
        let _ = enforcer;
    }
}
