[package]
name = "vnc-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
axum = { workspace = true, features = ["ws"] }
anyhow.workspace = true
tracing.workspace = true
futures = "0.3"
state-store = { path = "../state-store" }
vm-model = { path = "../vm-model" }
