apiVersion: v2
name: vmspawnd-operator
description: Kubernetes operator for Zyvor Fabric (vmspawnd)
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Zyvor Fabric contributors
home: https://github.com/ssahani/zyvor-fabric
