replicaCount: 1

image:
  repository: vmspawnd-operator
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: vmspawnd-operator

rbac:
  create: true

vmspawnd:
  url: "http://vmspawnd:8080"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
