[package]
name = "security"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
jsonwebtoken = "9.3"
bcrypt = "0.19"
tower = "0.5"
tower-http = { version = "0.6", features = ["auth"] }
rusqlite = { version = "0.32", features = ["bundled"] }
uuid.workspace = true
pam = "0.8"
totp-rs = { workspace = true }
base32 = { workspace = true }
base64 = "0.22"
