[package]
name = "zyvor-fabricd"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "zyvor-fabricd"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
axum = { workspace = true, features = ["ws", "multipart"] }
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
toml.workspace = true
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "cors", "trace", "timeout"] }
futures.workspace = true
uuid.workspace = true
chrono.workspace = true
reqwest = { version = "0.12", features = ["json", "stream"] }
lettre = { version = "0.11", features = ["tokio1-native-tls", "smtp-transport", "builder"] }
rand.workspace = true
base64 = "0.22"
async-stream = "0.3"
tokio-stream = "0.1"
tokio-util = "0.7"

networking = { path = "../networking" }
api-error = { path = "../crates/api-error" }
vm-model = { path = "../vm-model" }
security = { path = "../security" }
state-store = { path = "../state-store" }
zyvor-fabric-vm-driver = { path = "../zyvor-fabric-vm-driver" }
vnc-proxy = { path = "../vnc-proxy" }
cloud-init = { path = "../cloud-init" }
tpm-support = { path = "../tpm-support" }
prometheus-exporter = { path = "../prometheus-exporter" }
zyvor-fabric-driver-core = { path = "../crates/driver-core" }
zyvor-fabric-ephemera-driver = { path = "../crates/ephemera-driver" }
zyvor-fabric-storage = { path = "../crates/storage" }
zyvor-fabric-system = { path = "../crates/system" }
zyvor-fabric-vm = { path = "../crates/vm" }
datacenter = { path = "../datacenter" }
resource-pools = { path = "../resource-pools" }
predictive-drs = { path = "../predictive-drs" }
distributed-storage = { path = "../distributed-storage" }
encryption = { path = "../encryption" }
network-policy = { path = "../network-policy" }
service-mesh = { path = "../service-mesh" }
traffic-shaping = { path = "../traffic-shaping" }
dns-policy = { path = "../dns-policy" }
vm-firewall = { path = "../vm-firewall" }
vpn-mesh = { path = "../vpn-mesh" }
packet-mirror = { path = "../packet-mirror" }
nat-gateway = { path = "../nat-gateway" }
net-monitor = { path = "../net-monitor" }

ova-tools = { path = "../ova-tools" }
secrets-manager = { path = "../secrets-manager" }
zyvor-fabric-dnsmasq-manager = { path = "../crates/dnsmasq-manager" }
migration = { path = "../migration" }
fault-tolerance = { path = "../fault-tolerance" }
zyvor-fabric-lock-manager = { path = "../crates/lock-manager" }
replication = { path = "../replication" }
site-recovery = { path = "../site-recovery" }
content-library = { path = "../content-library" }
lifecycle-manager = { path = "../lifecycle-manager" }
certificate-manager = { path = "../certificate-manager" }
billing = { path = "../billing" }
compliance = { path = "../compliance" }

[dev-dependencies]
tempfile = "3"
