// GENERATED by website/scripts/gen-pack-gallery.mjs from examples/keep-agents/*/pack.json. Do not edit by hand; run `npm run gen:packs`.
export type GalleryPack = {id: string; title: string; description: string; accepts: string[]; reads: string; sample: boolean; model: boolean; group: string};

export const GALLERY_PACKS: GalleryPack[] = [
  {
    "id": "api-facts",
    "title": "API facts",
    "description": "Drop in a JSON document (an order, a webhook payload, an API response) and pull out the fields you care about.",
    "accepts": [
      "json"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "attendance-sheet",
    "title": "Attendance sheet",
    "description": "Drop in an Excel attendance sheet and see rows per employee and per status.",
    "accepts": [
      "xlsx"
    ],
    "reads": "Excel",
    "sample": false,
    "model": false,
    "group": "Office"
  },
  {
    "id": "bank-sms-ledger",
    "title": "Bank SMS ledger",
    "description": "Drop in saved bank and card SMS alerts and get money out, money in, amounts, where it went and what needs attention.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "bill-photo",
    "title": "Bill photo",
    "description": "Drop in a photo or screenshot of a utility, phone or card bill and get the amount due, the due date and the account or reference lines.",
    "accepts": [
      "png",
      "jpg",
      "jpeg",
      "tiff"
    ],
    "reads": "Photo (OCR)",
    "sample": false,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "bookmarks-digest",
    "title": "Bookmarks digest",
    "description": "Drop in a bookmarks HTML export and get the most common sites, the folders and the titles.",
    "accepts": [
      "html",
      "htm"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Browser"
  },
  {
    "id": "browser-history-takeout",
    "title": "Browser history (Google Takeout)",
    "description": "Drop in Google Takeout's BrowserHistory.json and get the most visited sites, how the pages were reached and the titles.",
    "accepts": [
      "json"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Browser"
  },
  {
    "id": "calendar-week",
    "title": "Calendar week",
    "description": "Drop in a calendar export (.ics) and get event titles, start times, locations and attendees.",
    "accepts": [
      "ics"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "card-statement",
    "title": "Card statement",
    "description": "Drop in a card or bank statement CSV and get the most common categories and merchants and the first rows.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "chat-export-digest",
    "title": "Chat export digest",
    "description": "Drop in an exported chat (.txt) and get who talks most, plans and times, money mentions and links.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "contacts-audit",
    "title": "Contacts audit",
    "description": "Drop in a contacts export (.vcf) and get names (duplicates first), numbers and emails.",
    "accepts": [
      "vcf"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "deck-outline",
    "title": "Deck outline",
    "description": "Drop in a PowerPoint (.pptx) and get the slide count, amounts, dates, open points, action lines and the speaker notes.",
    "accepts": [
      "pptx"
    ],
    "reads": "PowerPoint",
    "sample": false,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "dependabot-alerts",
    "title": "Dependabot alerts",
    "description": "Drop in the Dependabot alerts JSON and get severities, states, packages, ecosystems, manifests and the advisory summaries.",
    "accepts": [
      "json"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "employee-ledger",
    "title": "Employee ledger",
    "description": "Drop in a monthly employee ledger CSV and see how many rows per employee and month, and the first rows.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Office"
  },
  {
    "id": "expense-sheet",
    "title": "Expense sheet",
    "description": "Drop in an Excel expense sheet (first sheet, header row) and see the top categories and vendors and the first rows.",
    "accepts": [
      "xlsx"
    ],
    "reads": "Excel",
    "sample": false,
    "model": false,
    "group": "Office"
  },
  {
    "id": "git-log-digest",
    "title": "Git log digest",
    "description": "Drop in git log output in a pipe-separated format and get commits per author and month, commit-type prefixes and the merge count.",
    "accepts": [
      "txt",
      "log"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "github-actions-log",
    "title": "GitHub Actions failed log",
    "description": "Drop in gh run view --log-failed output and get the error lines, the failing steps, exit codes and the most repeated errors.",
    "accepts": [
      "txt",
      "log"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "github-issues",
    "title": "GitHub issues",
    "description": "Drop in gh issue list --json output and get open versus closed, authors, labels, issues opened per month and the titles.",
    "accepts": [
      "json"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "github-prs",
    "title": "GitHub pull requests",
    "description": "Drop in gh pr list --json output and get states, authors, labels, merges per month and the titles.",
    "accepts": [
      "json"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "homebrew-audit",
    "title": "Homebrew audit",
    "description": "Drop in brew list --versions (or brew outdated --verbose) and get counts, outdated packages and packages that keep old versions.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "inbox-digest",
    "title": "Inbox digest",
    "description": "Drop in an exported mailbox (plain text) and get a digest: what needs a reply, money, meetings, bulk mail and who writes most.",
    "accepts": [
      "eml",
      "mbox",
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "inventory-sheet",
    "title": "Inventory sheet",
    "description": "Drop in an Excel stock sheet and see rows per location and the first rows.",
    "accepts": [
      "xlsx"
    ],
    "reads": "Excel",
    "sample": false,
    "model": false,
    "group": "Office"
  },
  {
    "id": "invoice-check",
    "title": "Invoice check",
    "description": "Pull totals and due dates out of a plain-text invoice, and flag repeated lines.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "invoice-model-brief",
    "title": "Invoice brief (with a model)",
    "description": "Drop in an invoice PDF: rule-based sections plus a short generated summary from a model you approve.",
    "accepts": [
      "pdf"
    ],
    "reads": "PDF text",
    "sample": false,
    "model": true,
    "group": "Documents"
  },
  {
    "id": "loan-sanction-letter",
    "title": "Loan sanction letter",
    "description": "Drop in a sanction letter PDF and get the sanction terms, conditions, charges, amounts, rates and dates, each quoted from the letter.",
    "accepts": [
      "pdf"
    ],
    "reads": "PDF text",
    "sample": false,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "mac-apps-inventory",
    "title": "Mac apps inventory",
    "description": "Drop in system_profiler SPApplicationsDataType output and get the apps, where they came from, who signed them and where they live.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "mac-launch-items",
    "title": "Mac launch items",
    "description": "Drop in launchctl list output and get the third-party items and the ones that exited with an error or a signal.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "mac-log-triage",
    "title": "Mac log triage",
    "description": "Drop in compact log show output and get the busiest processes, errors and faults, sandbox denials and kernel trouble.",
    "accepts": [
      "txt",
      "log"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "mac-system-report",
    "title": "Mac system report",
    "description": "Drop in system_profiler output and get the model, chip, memory, macOS version and a few health flags.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "mac-update-history",
    "title": "Mac update history",
    "description": "Drop in softwareupdate --history and get what was installed, which versions, when, and which were betas.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Mac"
  },
  {
    "id": "mailbox-triage",
    "title": "Mailbox triage",
    "description": "Drop in an .mbox or .eml export and get who wrote, what the subjects are, and which messages need a reply, involve money or set a meeting.",
    "accepts": [
      "mbox",
      "eml"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "meeting-notes-model",
    "title": "Meeting notes (with a model)",
    "description": "Drop in a transcript (.txt or .vtt): decisions and actions by rule, plus a short summary from a model you approve.",
    "accepts": [
      "txt",
      "vtt"
    ],
    "reads": "Text",
    "sample": true,
    "model": true,
    "group": "Documents"
  },
  {
    "id": "nach-return-report",
    "title": "NACH return report",
    "description": "Drop in a NACH debit return report CSV and get returns counted by reason, status and sponsor, and the first rows.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "nda-review",
    "title": "NDA review",
    "description": "Drop in a Word contract and see its term, confidentiality, liability and governing-law clauses, and every duration and amount it mentions.",
    "accepts": [
      "docx"
    ],
    "reads": "Word",
    "sample": false,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "neft-rtgs-returns",
    "title": "NEFT / RTGS returns",
    "description": "Drop in a returns or rejects report and get the returned lines, beneficiary problems, UTRs, IFSCs and amounts.",
    "accepts": [
      "txt",
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "po-line-items",
    "title": "Purchase order line items",
    "description": "Drop in a purchase order as text and list the PO number, tax ids, HSN/SAC codes, the line-item lines and the amounts.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Office"
  },
  {
    "id": "rbi-circular-brief",
    "title": "RBI circular brief",
    "description": "Drop in a regulator circular PDF and get its references, who it applies to, dates and deadlines, and the lines that say what must be done.",
    "accepts": [
      "pdf"
    ],
    "reads": "PDF text",
    "sample": false,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "receipt-pdf",
    "title": "Receipt and warranty",
    "description": "Drop in a receipt or warranty PDF and get totals, dates and warranty or return terms.",
    "accepts": [
      "pdf"
    ],
    "reads": "PDF text",
    "sample": false,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "receipt-photo",
    "title": "Receipt photo",
    "description": "Drop in a photo or screenshot of a receipt and get the totals, dates, warranty or return lines and every amount seen.",
    "accepts": [
      "png",
      "jpg",
      "jpeg",
      "tiff"
    ],
    "reads": "Photo (OCR)",
    "sample": false,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "receivables-ageing",
    "title": "Receivables from mail",
    "description": "Drop in a mail export and list the invoices mentioned (most chased first), what is overdue or paid, and the amounts.",
    "accepts": [
      "mbox",
      "eml"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Office"
  },
  {
    "id": "recon-exceptions",
    "title": "Reconciliation exceptions",
    "description": "Drop in a reconciliation exceptions CSV and get exceptions counted by type, channel and ageing, and the first rows.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "reimbursement-claims",
    "title": "Reimbursement claims from mail",
    "description": "Drop in a mail export and list who claimed, the amounts, what is approved, pending, paid or declined, and the categories.",
    "accepts": [
      "mbox",
      "eml"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Office"
  },
  {
    "id": "sales-register-sheet",
    "title": "Sales register sheet",
    "description": "Drop in an Excel sales register and see rows per customer and the first rows.",
    "accepts": [
      "xlsx"
    ],
    "reads": "Excel",
    "sample": false,
    "model": false,
    "group": "Office"
  },
  {
    "id": "status-page-watch",
    "title": "Status page watch",
    "description": "Drop in a saved vendor status page (HTML) and see what is down, degraded, under maintenance or recovered.",
    "accepts": [
      "html",
      "htm"
    ],
    "reads": "HTML",
    "sample": true,
    "model": false,
    "group": "Documents"
  },
  {
    "id": "subscription-finder",
    "title": "Subscription finder",
    "description": "Drop in a mail export and find renewals, trials that end, what will be charged and the amounts.",
    "accepts": [
      "mbox",
      "eml"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "travel-itinerary",
    "title": "Travel itinerary",
    "description": "Drop in a booking or boarding-pass email and get flights, stays, booking references and what was paid.",
    "accepts": [
      "eml",
      "mbox"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Phone"
  },
  {
    "id": "upi-dispute-mail",
    "title": "UPI dispute mail",
    "description": "Drop in customer dispute mail (.eml, .mbox) and get what customers report, UPI reference numbers, amounts and escalation asks.",
    "accepts": [
      "eml",
      "mbox"
    ],
    "reads": "Mail",
    "sample": true,
    "model": false,
    "group": "Bank"
  },
  {
    "id": "vscode-extensions",
    "title": "VS Code extensions",
    "description": "Drop in code --list-extensions --show-versions and get the count, the extensions by publisher and their versions.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "vscode-settings-audit",
    "title": "VS Code settings audit",
    "description": "Drop in settings.json and see which settings are set and which relate to telemetry, trust, autosave and formatting.",
    "accepts": [
      "json",
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "windows-event-log",
    "title": "Windows event log",
    "description": "Drop in Get-WinEvent exported as CSV and get counts by level, provider and event id, plus the errors and warnings.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "windows-hotfixes",
    "title": "Windows hotfixes",
    "description": "Drop in Get-HotFix exported as CSV and get the KB numbers, types of update, who installed them and when.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "windows-installed-software",
    "title": "Windows installed software",
    "description": "Drop in an installed-programs CSV and get the most common publishers and programs and the first rows.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "windows-scheduled-tasks",
    "title": "Windows scheduled tasks",
    "description": "Drop in schtasks /query /fo csv /v output and get the task names, states, results and the accounts they run as.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "windows-services",
    "title": "Windows services",
    "description": "Drop in Get-Service exported as CSV and get the status and start-type counts and the service names.",
    "accepts": [
      "csv"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "windows-systeminfo",
    "title": "Windows system info",
    "description": "Drop in systeminfo output and get the OS and build, hardware, boot time, memory, domain and installed hotfixes.",
    "accepts": [
      "txt"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Windows"
  },
  {
    "id": "xcode-crash-log",
    "title": "Xcode crash report",
    "description": "Drop in a legacy .crash report and get the app, version, OS, exception, crashed thread and the top frames.",
    "accepts": [
      "crash",
      "txt",
      "log"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  },
  {
    "id": "xcodebuild-log",
    "title": "Xcode build log",
    "description": "Drop in xcodebuild output and get the build result, the errors and warnings by file and message, failed targets and failed tests.",
    "accepts": [
      "txt",
      "log"
    ],
    "reads": "Text",
    "sample": true,
    "model": false,
    "group": "Developer"
  }
];
