{{- if .Values.credentials.descriptors }}
{{- include "zyvor-keep.validate" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zyvor-keep.fullname" . }}-credentials
  labels:
    {{- include "zyvor-keep.labels" . | nindent 4 }}
data:
  credentials.json: {{ toPrettyJson .Values.credentials.descriptors | quote }}
{{- end }}
