{{- include "zyvor-keep.validate" . }}
{{- if not .Values.security.existingSecret }}
{{- $name := include "zyvor-keep.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "zyvor-keep.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.security.apiToken }}
  api-token: {{ .Values.security.apiToken | quote }}
  {{- else if and $existing (hasKey $existing.data "api-token") }}
  api-token: {{ index $existing.data "api-token" | b64dec | quote }}
  {{- else }}
  api-token: {{ randAlphaNum 40 | quote }}
  {{- end }}
  {{- if .Values.security.fluxvmToken }}
  fluxvm-token: {{ .Values.security.fluxvmToken | quote }}
  {{- end }}
{{- end }}
