[daemon]
# Listen address for REST API
listen = "127.0.0.1:8080"
# CORS allowed origins (default: ["http://127.0.0.1:8080"])
# cors_origins = ["http://127.0.0.1:8080", "https://myhost.example.com"]

[storage]
# Path to store VM state
path = "/var/lib/vmspawnd"
# Path to store VM images
image_path = "/var/lib/vmspawnd/images"

[network]
# Default network bridge
bridge = "br0"
