#!/usr/bin/env bash
# Generate docs/generated/project-stats.md from the live workspace.
# CI fails if this file is stale (git diff --exit-code).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/generated/project-stats.md"
mkdir -p "$(dirname "$OUT")"

CRATE_COUNT=$(python3 - <<PY
import tomllib
from pathlib import Path
c = tomllib.loads(Path("$ROOT/backend/Cargo.toml").read_text())
print(len(c["workspace"]["members"]))
PY
)

REACT_VERSION=$(python3 - <<PY
import json
from pathlib import Path
pkg = json.loads(Path("$ROOT/web/package.json").read_text())
print(pkg["dependencies"]["react"].lstrip("^~"))
PY
)

WEB_VERSION=$(python3 - <<PY
import json
from pathlib import Path
print(json.loads(Path("$ROOT/web/package.json").read_text())["version"])
PY
)

ROUTE_COUNT=$(rg -c 'Route|createBrowserRouter|path:' "$ROOT/web/src" -g '*.tsx' -g '*.ts' 2>/dev/null \
  | awk -F: '{s+=$2} END {print s+0}' || echo 0)
# Prefer explicit route declarations in App/router files when present
if [ -f "$ROOT/web/src/App.tsx" ]; then
  APP_ROUTES=$(rg -c 'path=' "$ROOT/web/src/App.tsx" 2>/dev/null || echo 0)
else
  APP_ROUTES=0
fi

WORKSPACE_VERSION=$(python3 - <<PY
import tomllib
from pathlib import Path
c = tomllib.loads(Path("$ROOT/backend/Cargo.toml").read_text())
print(c["workspace"]["package"]["version"])
PY
)

cat > "$OUT" <<EOF
<!-- Generated by scripts/generate-project-stats.sh — do not edit by hand. -->
# Project stats

| Metric | Value |
|--------|-------|
| Workspace crates | ${CRATE_COUNT} |
| Workspace version | ${WORKSPACE_VERSION} |
| Web package version | ${WEB_VERSION} |
| React version | ${REACT_VERSION} |
| Rough web route matches | ${ROUTE_COUNT} |
| App.tsx path= count | ${APP_ROUTES} |

Canonical facts for README/architecture prose:

- Backend workspace: **${CRATE_COUNT} crates**
- Web UI: **React ${REACT_VERSION}**
EOF

echo "Wrote $OUT (crates=${CRATE_COUNT}, react=${REACT_VERSION})"
