#!/usr/bin/env bash
# Generate docs/generated/project-stats.md from the live workspace.
# CI fails if this file is stale (git diff --exit-code).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/generated/project-stats.md"
mkdir -p "$(dirname "$OUT")"

python3 - <<PY
import json
import re
import tomllib
from pathlib import Path

root = Path(r"""$ROOT""")
backend = tomllib.loads((root / "backend" / "Cargo.toml").read_text())
pkg = json.loads((root / "web" / "package.json").read_text())

crate_count = len(backend["workspace"]["members"])
workspace_version = backend["workspace"]["package"]["version"]
web_version = pkg["version"]
react_version = pkg["dependencies"]["react"].lstrip("^~")

route_re = re.compile(r"Route|createBrowserRouter|path:")
route_count = 0
for path in (root / "web" / "src").rglob("*"):
    if path.suffix not in {".ts", ".tsx"}:
        continue
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        continue
    route_count += len(route_re.findall(text))

app = root / "web" / "src" / "App.tsx"
app_routes = 0
if app.is_file():
    app_routes = app.read_text(encoding="utf-8", errors="ignore").count("path=")

out = root / "docs" / "generated" / "project-stats.md"
out.write_text(
    f"""<!-- Generated by scripts/generate-project-stats.sh — do not edit by hand. -->
# Project stats

| Metric | Value |
|--------|-------|
| Workspace crates | {crate_count} |
| Workspace version | {workspace_version} |
| Web package version | {web_version} |
| React version | {react_version} |
| Rough web route matches | {route_count} |
| App.tsx path= count | {app_routes} |

Canonical facts for README/architecture prose:

- Backend workspace: **{crate_count} crates**
- Web UI: **React {react_version}**
""",
    encoding="utf-8",
)
print(f"Wrote {out} (crates={crate_count}, react={react_version})")
PY
