[package]
name = "networking"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
rand.workspace = true
tokio.workspace = true
rtnetlink = "0.23"
netlink-packet-route = "0.21"
futures.workspace = true

[dev-dependencies]
tempfile = "3"
