name: Terraform Provider

on:
  push:
    paths:
      - 'terraform-provider/**'
  pull_request:
    paths:
      - 'terraform-provider/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-provider
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go mod tidy
      - run: go build -v .
      - run: go test ./...
